### PR TITLE
api responses

### PR DESCRIPTION
**Pull request by recursivefunk**
Proposed (partial) implementation for API responses across ALL ISL (franklin, cher etc) projects. Based on [this article](https://medium.com/@shazow/how-i-design-json-api-responses-71900f00f2db#.gmbyuyrz4) written by [shazow](https://twitter.com/shazow)

### CODE REVIEW

**Comment by oudeismetis** [comment]
defining a schema for our apis does sound like a good idea. In my opinion, status is unnecessary. If you are using proper HTTP status codes and not just returning 200 for everything, it should be clear what has happened. Any necessary details could go in `messages`.

**Comment by recursivefunk** [comment]
I feel you. But there's a section in the article that addresses that
specifically check it out and let me know what you think

**Comment by oudeismetis** [comment]
yea, I read that part. I don't fully follow his logic against using standard HTTP status'. Seems to violate everything I've ever learned about building APIs. I want to do some extra reading to see if he has a point there though.

**Comment by recursivefunk** [comment]
So I was actually mistaken and was thinking about code. 

There is one thing to consider though, different platforms (and abstractions built on them: Node - express, restify | Django - django rest framework, flask | Golang - martini etc) have nuanced (sometimes drastically) differences in how to access all the standard HTTP information. API clients aren't just browsers, they can be mobile apps, other servers etc. It would be nice if all the information you need to make a decision based on how to proceed is always in the app's response which should obviously be consistent with the platforms information, but all in one place. So, you wouldn't need to check status or code via a browser/django API then check data via the actual JSON it's all in one place. It's a very small thing but if we do it right it could make talking to all of our stacks very seamless. Anyway, not tied to it, if you guys think we can dump it -  that's cool.

**Comment by JulianGindi** [comment]
I like this idea but I agree with Ed, I'm not sold on dropping HTTP statuses.

**Comment by recursivefunk** [comment]
Not saying drop HTTP statuses. All information remains in tact where you'd expect it via the framework, the same information is just present in the actual API response. Along side the payload/result or whatever

**Comment by oudeismetis** [comment]
Seems like that could cause inconsistencies and extra code to maintain. I'm curious to understand better what the challenge is. Are you saying that mobile libraries (and other platforms) are unable to inspect the header when a message comes in? Does this start to blur the line between transport and application logic/concerns? 

I'd be curious to hear about a specific issue with current approach most developers take to designing APIs.

**Comment by recursivefunk** [comment]
Nah not so much for our current platforms they'd be fine. But venturing off into unknown territory with what is actually consuming API data. There's all these gesture control devices that are coming out, we don't really know what state their SDKs are in. It's about having a complete picture of a response regardless of the platform. Inconsistencies wouldn't be much of an issue if we just use middleware to take what the platform is reporting and put it in responses before they go out. Also, considering the source:

`Why not just use HTTP response codes instead of embedding a code value in our JSON? Three reasons:`

```
Consumers don’t like checking response codes, it’s a lazy thing. All of my code is already dealing with JSON values so why not one more. Also some HTTP libraries make it somewhat difficult to get at the value.
```

```
HTTP response codes are unreliable. Some poorly-implemented proxy code could override the code, or your cache will kick in and serve that one buggy response which might be inconsistent with the values inside.
```

```
No reason to tightly couple with your transport protocol. By all means, mirror your codes in HTTP but if you include it in the encoded response then you can just as easily switch the API to straight-up TCP or even something crazy like an SSH RPC API!
```

We're making a lot of assumptions about how things will work in the future - the "happy path". We should take heed and learn the lessons of people who have been doing this a lot longer than we have. In this particular case, this guy has a LOT of experience actually building products for Google and 23andMe etc. Just sayin.

**Comment by JulianGindi** [comment]
I actually don't think we should consider standardizing Franklin's API responses with the rest of our stacks. Franklin is a "closed system" and I much rather standardize how we handle API communication within the Franklin system as opposed to with the rest of our projects. Franklin's build service will never need to communicate with gesture control devices or other similar future devices either. Never say never I guess, but future proofing in that direction seems unnecessary and I don't think it represents us taking the "happy path".

That being said, there is a ton of value to implementing a solution such as this. I am actually convinced of the response code arguments made above. I think we SHOULD adopt a pattern similar (or identical) to this. 

I think we should proceed with this by creating an issue in the backlog and spend some time formalizing our communication protocols. 

In addition to the above, we will most likely eventually switch the communication between the API and the Build service to use a queue. Once we do that, we will no longer be issuing a json response. 

Just my two cents. Encourage further dialogue on the subject. I appreciate you bringing this up and actually submitting a PR @jray

**Comment by recursivefunk** [comment]
Cool sounds reasonable - Franklin is it's own thing and the API isn't really meant for consumption outside of it's internal components. I'll close this out we can discuss for other projects when we're back in the office.

**Pull request closed without merging**
