### PR TITLE
adding rm commands to clean up uneeded filesystem

### PR DESCRIPTION
**Pull request by JulianGindi**

### CODE REVIEW

**Comment by oudeismetis** [comment]
please explain as I'm having trouble finding docs that detail what is happening here.

**Comment by JulianGindi** [comment]
https://docs.docker.com/engine/reference/run/#clean-up-rm

**Comment by oudeismetis** [comment]
not sure how I missed that. Sweet!
From the sounds of it though, we can ditch the `-v` and `--rm` does that for us.

**Comment by oudeismetis** [comment]
:+1:

**Comment by JulianGindi** [comment]
We need the `-v` as that's how we mount volumes

**Pull request merged**
